apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lldap-data
  namespace: lldap
spec:
  storageClassName: proxmox-csi
  volumeName: pv-lldap
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
